REGIONES = ["Región de Tarapacá                              ",
"Región de Antofagasta                           ",
"Región de Atacama                               ",
"Región de Coquimbo                              ",
"Región de Valparaíso                            ",
"Región del Libertador Bernardo Ohiggins         ",
"Región del Maule                                ",
"Región del Biobío                               ",
"Región de La Araucanía                          ",
"Región de Los Lagos                             ",
"Región Aisén del General Carlos Ibáñez del Campo",
"Región de Magallanes y la Antártica Chilena     ",
"Región Metropolitana de Santiago                ",
"Región de Los Ríos                              ",
"Región Arica y Parinacota                       ",
"Región del Ñuble                                "]
REGIONES = [region.strip() for region in REGIONES]